modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"
[[mods]]
modId="fxbuildup"
version="0.81"
displayName="FXBuildup"
credits="Thanks to FromSoft for the inspiration."
authors="Mithion"
description='''
This is a highly configurable mod that adds soulsbourne-esque status buildup to Minecraft.
It also adds dodging and stamina.
'''

[[dependencies.fxbuildup]]
    modId="forge"
    mandatory=true
    versionRange="[47.1.64,)"
    ordering="NONE"
    side="BOTH"
	
[[dependencies.fxbuildup]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"
